import * as entity from "./../src/entity/strava.entity";

export const detailedAthlete: entity.IDetailedAthlete = {
  id: 1111,
  username: null,
  resource_state: 2,
  firstname: 'john',
  lastname: 'snow',
  bio: 'a description',
  city: '',
  state: '',
  country: null,
  sex: 'M',
  premium: true,
  summit: true,
  created_at: '2022-10-04T10:08:05Z',
  updated_at: '2024-01-20T16:00:03Z',
  badge_type_id: 1,
  weight: 58.2,
  profile_medium: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/1111/1111/2/medium.jpg',
  profile: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/1111/1111/2/large.jpg',
  friend: null,
  follower: null
}

// ============= CLUB MOCK DATA
// real club data
export const detailedClub: entity.IDetailedClub = {
  id: 1219949,
  resource_state: 3,
  name: 'HiPRO France',
  profile_medium: 'https://dgalywyr863hv.cloudfront.net/pictures/clubs/1219949/30072295/1/medium.jpg',
  profile: 'https://dgalywyr863hv.cloudfront.net/pictures/clubs/1219949/30072295/1/large.jpg',
  cover_photo: 'https://dgalywyr863hv.cloudfront.net/pictures/clubs/1219949/30191159/1/large.jpg',
  cover_photo_small: 'https://dgalywyr863hv.cloudfront.net/pictures/clubs/1219949/30191159/1/small.jpg',
  activity_types: [],
  activity_types_icon: 'sports_multi_normal',
  dimensions: ['moving_time', 'num_activities', 'distance', 'elev_gain'],
  sport_type: 'other',
  localized_sport_type: 'Multisport',
  city: 'Paris',
  state: '',
  country: 'France',
  private: false,
  member_count: 2350,
  featured: false,
  verified: true,
  url: 'HiPRO-France',
  membership: 'member',
  admin: false,
  owner: false,
  description: 'Bienvenue sur le Club HiPRO France ! \r\n' +
    'Prêts à muscler votre entraînement* et votre nutrition ? 👟\r\n' +
    'https://www.instagram.com/hiprofrance/?hl=fr\r\n' +
    '\r\n' +
    '*HiPRO est riche en protéines. Les protéines contribuent au maintien et à l’augmentation de la masse musculaire.',
  club_type: 'casual_club',
  following_count: 0,
  website: 'https://hipro.danone.fr/'
}

export const clubMembers: entity.IClubAthlete[] = [
  {
    resource_state: 2,
    firstname: '# SR # Ramesh',
    lastname: 'T.',
    membership: 'member',
    admin: false,
    owner: false
  },
  {
    resource_state: 2,
    firstname: "'Luis Fernando Osorio",
    lastname: '&.',
    membership: 'member',
    admin: false,
    owner: false
  }
];

const clubAdmins: entity.ISummaryAthlete[] = [
  { resource_state: 2, firstname: 'Louis', lastname: 'R.' },
  { resource_state: 2, firstname: 'Bertrand', lastname: 'D.' },
  { resource_state: 2, firstname: 'Cécile', lastname: 'R.' },
  { resource_state: 2, firstname: 'Kali', lastname: 'I.' },
  { resource_state: 2, firstname: 'Zack', lastname: 'N.' }
];

export const getLoggedInAthleteClubsMock: entity.ISummaryClub[] = [
  {
    id: 231407,
    resource_state: 2,
    name: 'The Strava Club',
    profile_medium: 'https://dgalywyr863hv.cloudfront.net/pictures/clubs/231407/5319085/1/medium.jpg',
    profile: 'https://dgalywyr863hv.cloudfront.net/pictures/clubs/231407/5319085/1/large.jpg',
    cover_photo: 'https://dgalywyr863hv.cloudfront.net/pictures/clubs/231407/5098428/21/large.jpg',
    cover_photo_small: 'https://dgalywyr863hv.cloudfront.net/pictures/clubs/231407/5098428/21/small.jpg',
    activity_types: [],
    activity_types_icon: 'sports_multi_normal',
    dimensions: ['moving_time', 'num_activities', 'distance', 'elev_gain'],
    sport_type: 'other',
    localized_sport_type: 'Multisport',
    city: 'San Francisco',
    state: 'California',
    country: 'United States',
    private: false,
    member_count: 5142272,
    featured: false,
    verified: true,
    url: 'strava'
  },
  {
    id: 85235,
    resource_state: 2,
    name: 'xxxxx',
    profile_medium: 'https://3hv.cloudfront.net/pictures/clubs/1/1/1/medium.jpg',
    profile: 'https://3hv.cloudfront.net/pictures/clubs/1/1/1/large.jpg',
    cover_photo: null,
    cover_photo_small: null,
    activity_types: ['Run', 'VirtualRun', 'Wheelchair'],
    activity_types_icon: 'sports_run_normal',
    dimensions: [
      'distance',
      'num_activities',
      'best_activities_distance',
      'elev_gain',
      'moving_time',
      'velocity'
    ],
    sport_type: 'running',
    localized_sport_type: 'Running',
    city: '',
    state: '',
    country: 'USA',
    private: false,
    member_count: 1260000,
    featured: false,
    verified: false,
    url: 'xxxxx'
  }
];

export const getClubActivitieById: entity.IClubActivity[] = [
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: 'Marcos', lastname: 'C.' },
    name: 'Fé, Esperança e Amor em Deus sempre.',
    distance: 4314.9,
    moving_time: 731,
    elapsed_time: 763,
    total_elevation_gain: 26.5,
    type: 'Ride',
    sport_type: 'MountainBikeRide',
    workout_type: 11
  }, {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: 'Mathias', lastname: 'C.' },
    name: "Entraînement dans l'après-midi",
    distance: 0,
    moving_time: 1762,
    elapsed_time: 1762,
    total_elevation_gain: 0,
    type: 'Workout',
    sport_type: 'Workout'
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: 'bernard', lastname: 'S.' },
    name: 'Course à pied le midi',
    distance: 12448.3,
    moving_time: 4166,
    elapsed_time: 4245,
    total_elevation_gain: 47.1,
    type: 'Run',
    sport_type: 'Run',
    workout_type: null
  }
];

export const athletesZones = {
  "custom_zones": false,
  "zones": [
    { "max": 118, "min": 0 },
    { "max": 147, "min": 118 },
    { "max": 161, "min": 147 },
    { "max": 176, "min": 161 },
    { "max": -1, "min": 176 }
  ]
};

export const getsStatsAthlete : entity.IActivitiesStats = {
  recent_ride_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0
  },
  all_ride_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0
  },
  recent_run_totals: {
    count: 8,
    distance: 102600.951171875,
    moving_time: 34747,
    elapsed_time: 35221,
    elevation_gain: 428.9634132385254,
    achievement_count: 38
  },
  all_run_totals: {
    count: 83,
    distance: 747002,
    moving_time: 273248,
    elapsed_time: 1310631,
    elevation_gain: 2468
  },
  recent_swim_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0
  },
  all_swim_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0
  },
  ytd_ride_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0
  },
  ytd_run_totals: {
    count: 32,
    distance: 336688,
    moving_time: 115413,
    elapsed_time: 116402,
    elevation_gain: 1414
  },
  ytd_swim_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0
  }
}

export const commentItem : entity.IComment = {
  id: 177,
  activity_id: 111,
  post_id: null,
  resource_state: 2,
  text: 'test api',
  mentions_metadata: null,
  created_at: '2024-04-13T14:00:28Z',
  cursor: 'eyJpZCI6MTc3MzU0MzYyMywiY3JlYXRlZEF0',
  athlete: { resource_state: 2, firstname: 'Jack', lastname: 'X.' },
  reaction_count: 0,
  has_reacted: false
}

export const kudoersActivity : entity.ISummaryAthlete[] =  [
  { resource_state: 2, firstname: 'Yoh', lastname: 'H.' },
  { resource_state: 2, firstname: 'Orl', lastname: 'M.' },
  { resource_state: 2, firstname: '🇪🇺', lastname: 'J.' },
  { resource_state: 2, firstname: 'Qu', lastname: 'H.' }
]

export const lapActivity : entity.ILap[] = [
  {
    id: 38752137019,
    resource_state: 2,
    name: 'Lap 1',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 347,
    moving_time: 347,
    start_date: '2024-04-07T15:14:51Z',
    start_date_local: '2024-04-07T17:14:51Z',
    distance: 1000,
    average_speed: 2.88,
    max_speed: 4.632,
    lap_index: 1,
    split: 1,
    start_index: 0,
    end_index: 20,
    total_elevation_gain: 5,
    average_cadence: 81.6,
    device_watts: true,
    average_watts: 306.9,
    average_heartrate: 123.3,
    max_heartrate: 136,
    pace_zone: 0
  },
  {
    id: 38752137030,
    resource_state: 2,
    name: 'Lap 2',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 341,
    moving_time: 341,
    start_date: '2024-04-07T15:20:40Z',
    start_date_local: '2024-04-07T17:20:40Z',
    distance: 1000,
    average_speed: 2.93,
    max_speed: 3.714,
    lap_index: 2,
    split: 2,
    start_index: 21,
    end_index: 361,
    total_elevation_gain: 0,
    average_cadence: 83,
    device_watts: true,
    average_watts: 314.4,
    average_heartrate: 141.4,
    max_heartrate: 145,
    pace_zone: 0
  },
  {
    id: 38752137042,
    resource_state: 2,
    name: 'Lap 3',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 350,
    moving_time: 350,
    start_date: '2024-04-07T15:26:21Z',
    start_date_local: '2024-04-07T17:26:21Z',
    distance: 1000,
    average_speed: 2.86,
    max_speed: 3.438,
    lap_index: 3,
    split: 3,
    start_index: 362,
    end_index: 712,
    total_elevation_gain: 4.8,
    average_cadence: 83.2,
    device_watts: true,
    average_watts: 313.2,
    average_heartrate: 143.3,
    max_heartrate: 148,
    pace_zone: 0
  },
  {
    id: 38752137055,
    resource_state: 2,
    name: 'Lap 4',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 339,
    moving_time: 339,
    start_date: '2024-04-07T15:32:12Z',
    start_date_local: '2024-04-07T17:32:12Z',
    distance: 1000,
    average_speed: 2.95,
    max_speed: 3.428,
    lap_index: 4,
    split: 4,
    start_index: 713,
    end_index: 1051,
    total_elevation_gain: 2.8,
    average_cadence: 83.7,
    device_watts: true,
    average_watts: 327.5,
    average_heartrate: 146.5,
    max_heartrate: 149,
    pace_zone: 0
  },
  {
    id: 38752137066,
    resource_state: 2,
    name: 'Lap 5',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 338,
    moving_time: 338,
    start_date: '2024-04-07T15:37:51Z',
    start_date_local: '2024-04-07T17:37:51Z',
    distance: 1000,
    average_speed: 2.96,
    max_speed: 3.452,
    lap_index: 5,
    split: 5,
    start_index: 1052,
    end_index: 1390,
    total_elevation_gain: 7.4,
    average_cadence: 83.5,
    device_watts: true,
    average_watts: 333.8,
    average_heartrate: 147.4,
    max_heartrate: 152,
    pace_zone: 0
  },
  {
    id: 38752137072,
    resource_state: 2,
    name: 'Lap 6',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 345,
    moving_time: 329,
    start_date: '2024-04-07T15:43:30Z',
    start_date_local: '2024-04-07T17:43:30Z',
    distance: 1000,
    average_speed: 3.04,
    max_speed: 4.218,
    lap_index: 6,
    split: 6,
    start_index: 1391,
    end_index: 1721,
    total_elevation_gain: 9.4,
    average_cadence: 84.1,
    device_watts: true,
    average_watts: 337,
    average_heartrate: 147.5,
    max_heartrate: 154,
    pace_zone: 0
  },
  {
    id: 38752137077,
    resource_state: 2,
    name: 'Lap 7',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 332,
    moving_time: 332,
    start_date: '2024-04-07T15:49:15Z',
    start_date_local: '2024-04-07T17:49:15Z',
    distance: 1000,
    average_speed: 3.01,
    max_speed: 3.79,
    lap_index: 7,
    split: 7,
    start_index: 1722,
    end_index: 2053,
    total_elevation_gain: 3.4,
    average_cadence: 84.1,
    device_watts: true,
    average_watts: 320.3,
    average_heartrate: 152.4,
    max_heartrate: 155,
    pace_zone: 0
  },
  {
    id: 38752137084,
    resource_state: 2,
    name: 'Lap 8',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 302,
    moving_time: 302,
    start_date: '2024-04-07T15:54:47Z',
    start_date_local: '2024-04-07T17:54:47Z',
    distance: 1000,
    average_speed: 3.31,
    max_speed: 4.468,
    lap_index: 8,
    split: 8,
    start_index: 2054,
    end_index: 2355,
    total_elevation_gain: 0,
    average_cadence: 85.7,
    device_watts: true,
    average_watts: 351.3,
    average_heartrate: 158.2,
    max_heartrate: 161,
    pace_zone: 0
  },
  {
    id: 38752137094,
    resource_state: 2,
    name: 'Lap 9',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 367,
    moving_time: 347,
    start_date: '2024-04-07T15:59:49Z',
    start_date_local: '2024-04-07T17:59:49Z',
    distance: 1000,
    average_speed: 2.88,
    max_speed: 3.378,
    lap_index: 9,
    split: 9,
    start_index: 2356,
    end_index: 2704,
    total_elevation_gain: 4.8,
    average_cadence: 83.9,
    device_watts: true,
    average_watts: 312.3,
    average_heartrate: 149.8,
    max_heartrate: 157,
    pace_zone: 0
  },
  {
    id: 38752137101,
    resource_state: 2,
    name: 'Lap 10',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 346,
    moving_time: 346,
    start_date: '2024-04-07T16:05:56Z',
    start_date_local: '2024-04-07T18:05:56Z',
    distance: 1000,
    average_speed: 2.89,
    max_speed: 3.402,
    lap_index: 10,
    split: 10,
    start_index: 2705,
    end_index: 2959,
    total_elevation_gain: 4.6,
    average_cadence: 84.2,
    device_watts: true,
    average_watts: 327.1,
    average_heartrate: 151.6,
    max_heartrate: 155,
    pace_zone: 0
  },
  {
    id: 38752137106,
    resource_state: 2,
    name: 'Lap 11',
    activity: { id: 111, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 111, resource_state: 1 },
    elapsed_time: 12,
    moving_time: 12,
    start_date: '2024-04-07T16:11:42Z',
    start_date_local: '2024-04-07T18:11:42Z',
    distance: 33.24,
    average_speed: 2.77,
    max_speed: 2.966,
    lap_index: 11,
    split: 11,
    start_index: 2959,
    end_index: 2959,
    total_elevation_gain: 0,
    average_cadence: 84,
    device_watts: true,
    average_watts: 293.3,
    average_heartrate: 151.4,
    max_heartrate: 152,
    pace_zone: 0
  }
];

//

export const segmentEffort : entity.IDetailedSegmentEffort[]  = [
  {
    id: 32,
    resource_state: 2,
    name: 'Tournicoti',
    activity: { id: 11, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 10, resource_state: 1 },
    elapsed_time: 101,
    moving_time: 101,
    start_date: '2024-03-27T15:52:17Z',
    start_date_local: '2024-03-27T16:52:17Z',
    distance: 304.8,
    start_index: 1764,
    end_index: 1865,
    average_cadence: 84.8,
    device_watts: true,
    average_watts: 384.2,
    average_heartrate: 159.9,
    max_heartrate: 162,
    segment: {
      id: 1,
      resource_state: 2,
      name: 'Tournicoti',
      activity_type: 'Run',
      distance: 304.8,
      average_grade: 2,
      maximum_grade: 18.2,
      elevation_high: 41,
      elevation_low: 35,
      start_latlng: [11,11],
      end_latlng: [11,11],
      elevation_profile: null,
      climb_category: 0,
      city: 'V',
      state: 'Î',
      country: 'France',
      private: false,
      hazardous: false,
      starred: false
    },
    pr_rank: 1,
    achievements: [],
    visibility: 'everyone',
    kom_rank: null
  },
  {
    id: 32,
    resource_state: 2,
    name: 'Tournicoti',
    activity: { id: 11, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 10, resource_state: 1 },
    elapsed_time: 106,
    moving_time: 106,
    start_date: '2024-03-31T14:39:54Z',
    start_date_local: '2024-03-31T16:39:54Z',
    distance: 304.8,
    start_index: 3786,
    end_index: 3892,
    average_cadence: 84.5,
    device_watts: true,
    average_watts: 357,
    average_heartrate: 157.5,
    max_heartrate: 158,
    segment: {
      id: 14,
      resource_state: 2,
      name: 'Tournicoti',
      activity_type: 'Run',
      distance: 304.8,
      average_grade: 2,
      maximum_grade: 18.2,
      elevation_high: 41,
      elevation_low: 35,
      start_latlng: [11,11],
      end_latlng: [11,11],
      elevation_profile: null,
      climb_category: 0,
      city: 'V',
      state: 'Île',
      country: 'France',
      private: false,
      hazardous: false,
      starred: false
    },
    pr_rank: 2,
    achievements: [],
    visibility: 'everyone',
    kom_rank: null
  },
  {
    id: 32,
    resource_state: 2,
    name: 'Tournicoti',
    activity: { id: 11, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 10, resource_state: 1 },
    elapsed_time: 107,
    moving_time: 107,
    start_date: '2024-04-07T15:48:40Z',
    start_date_local: '2024-04-07T17:48:40Z',
    distance: 304.8,
    start_index: 2015,
    end_index: 2122,
    average_cadence: 83.3,
    device_watts: true,
    average_watts: 347.2,
    average_heartrate: 152.1,
    max_heartrate: 154,
    segment: {
      id: 14,
      resource_state: 2,
      name: 'Tournicoti',
      activity_type: 'Run',
      distance: 304.8,
      average_grade: 2,
      maximum_grade: 18.2,
      elevation_high: 41,
      elevation_low: 35,
      start_latlng: [11,11],
      end_latlng: [11,11],
      elevation_profile: null,
      climb_category: 0,
      city: 'V',
      state: 'Î',
      country: 'France',
      private: false,
      hazardous: false,
      starred: false
    },
    pr_rank: 3,
    achievements: [],
    visibility: 'everyone',
    kom_rank: null
  },
  {
    id: 32,
    resource_state: 2,
    name: 'Tournicoti',
    activity: { id: 11, visibility: 'everyone', resource_state: 1 },
    athlete: { id: 11, resource_state: 1 },
    elapsed_time: 111,
    moving_time: 111,
    start_date: '2024-03-29T14:42:19Z',
    start_date_local: '2024-03-29T15:42:19Z',
    distance: 304.8,
    start_index: 1995,
    end_index: 2106,
    average_cadence: 82.5,
    device_watts: true,
    average_watts: 344.2,
    average_heartrate: 160.6,
    max_heartrate: 162,
    segment: {
      id: 14035198,
      resource_state: 2,
      name: 'Tournicoti',
      activity_type: 'Run',
      distance: 304.8,
      average_grade: 2,
      maximum_grade: 18.2,
      elevation_high: 41,
      elevation_low: 35,
      start_latlng: [11,11],
      end_latlng: [11,11],
      elevation_profile: null,
      climb_category: 0,
      city: 'V',
      state: 'Î',
      country: 'France',
      private: false,
      hazardous: false,
      starred: false
    },
    pr_rank: 2,
    achievements: [],
    visibility: 'everyone',
    kom_rank: null
  }
]